### ISSUE TITLE
Error in GameManager

### ISSUE THREAD

**Issue by MyrddinE** [MarkoSulamagi/screeps#10]
GameManager includes an error in the example code... you can't refer to Game.creeps.Argos. Shouldn't that be Game.creeps['Argos'] in TypeScript?

**Comment by MarkoSulamagi** [comment]
It was a legacy call. It was possible some time ago, but now you can't do it. 
I made it so that it would be easier to port existing JS Screep's project to TS. I changed it now and pushed new code to repo. 

Thank you for your help.
