### ISSUE TITLE
Deprecation Request

### ISSUE THREAD

**Issue by ratuple** [MarkoSulamagi/screeps#13]
I suggest to deprecate this project and instead provide a link to https://github.com/screepers/screeps-typescript-starter which is based on your project.

The mentioned project is much more sophisticated, actually compiles currently (see other issue), has a better project structure for the Screeps library lookup (not in node-modules) and uses up-to-date libraries (e.g. typings instead of tsd).
Additionally it also provides the possibility to not bundle everything together into the one main.js but upload all the resulting JS files as Screeps modules to have a clean exception stacktrace and not only the bundled file.  

This project is outdated and it has cost me a lot of time to try to start a project with this template. I tried to fix several issues, improve the setup, and integrate it nicely into my IDE (IntelliJ) but after some time of depression of how bad the setup was I continued my search on other project templates and found the mentioned project. That project had everything I wished for and I just had to do some minor steps to integrate it nicely with my IDE.

I thank you for sharing this project and helping other people play the game but it currently does not provide any purpose anymore. It just costs other people's time as there is a much better alternative but it is not obvious which template is better without actually trying it.

**Comment by MarkoSulamagi** [comment]
Thank you ratuple! 
I haven't updated the skeleton for some time and I don't think I can do it in the near future. Even now when there's a better option managed by more active screepers. I'm happy that someone has taken over with a better skeleton and I'll make a link to that project on this GitHub page. Also with the notice that the library is deprecated.

**Comment by Jnark** [comment]
Marko, it's me
